CAF/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('signup/', include('signup.urls')),
    path('session/', include('login.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path, include
from . import views 

app_name = 'home'

urlpatterns = [
    path('', views.index, name="index"),
]

login/urls.py
from django.urls import path, include
from . import views 

app_name = 'login'

urlpatterns = [
    path('', views.index, name="index"),
    path('session/', views.new, name="new"),
]

signup/urls.py
from django.urls import path, include
from . import views 

app_name = "signup"

urlpatterns = [
    path('', views.index, name="index"),
    path('result/', views.new, name="new"),
]

home/models.py
from django.db import models

# Create your models here.

login/models.py
from django.db import models

# Create your models here.

signup/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Custom(models.Model):
  user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
  photo = models.ImageField()

  def __str__(self):
    return '{}'.format(self.user.email)

home/views.py
from django.shortcuts import render

# Create your views here.

# index --> mostrar a tela de template (login)
# new --> mostrar a tela de template (cadastro) retorna para home
# login --> mostrar a tela de template (só uma tela com o nome do usuário)

def index(request):
  return render(request, "home.html")

login/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate
from signup.models import Custom


# Create your views here.

def index(request):
  return render (request, "session/login.html")

def new(request):
  username = request.POST['username']
  password = request.POST['password']

  user = authenticate(username=username, password=password)

  custom = Custom.objects.get(user = user)

  return render (request, "dashboard/index.html", {"custom": custom })

signup/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.models import User
from .models import Custom

# Create your views here.

def index(request):
  return render (request, "session/signup.html")

def new(request):
  username = request.POST['username']
  password = request.POST['password']
  email = request.POST['email']
  first_name = request.POST['first_name'] 
  last_name = request.POST['last_name']
  photo = request.POST['photo']

  user = User.objects.create_user(username, email, password)
  user.last_name = last_name
  user.first_name = first_name
  user.save()

  user_custom = get_object_or_404(User, username=username)

  custom = Custom.objects.create()
  custom.user = user_custom
  custom.photo = photo
  custom.save()

  return render(request, "home.html", { 'message': "O usuário ${username} foi criado com sucesso!"})

templates/dashboard/index.html
{% extends 'generic_base.html' %}

{% load static %}

{% block title %} Dashboard {% endblock %}

{% block content %}
<h1>Bem vindo {{ custom.user.first_name }}</h1>
<img src="{{custom.photo.url}}" alt="">
{% endblock %}

templates/generic_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}{% endblock %}</title>
  <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'fontawesome/css/all.min.css' %}">
  <script defer src="{% static 'fontawesome/js/all.min.js' %}"></script>
</head>

<body>
  {% block content %}

  {% endblock %}
  <script src="{% static 'bootstrap/js/jquery.min.js' %}"></script>
  <script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>
</body>

</html>

templates/home.html
{% extends 'generic_base.html' %}

{% block content %}
{{ message }}
<a href="{% url 'login:index' %}">Login</a>
<a href="{% url 'signup:index' %}">Cadastrar</a>
{% endblock %}

templates/session/error.html
{% extends 'generic_base.html' %}

{% block title %} Erro {% endblock %}

{% block content %}

<div class="d-flex wrapper">
    <h1 class="mensagem-erro">Error Example</h1>
</div>

{% endblock %}

templates/session/login.html
{% extends 'generic_base.html' %}

{% block title %} Login {% endblock %}

{% block content %}
<div class="container-fludi">
    <div class="row">

        <div class="col-6">
        </div>

        <div class="col-6">
            <form class="d-flex flex-row justify-content-center align-items-center" action="{% url 'login:new' %}"
                method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <div class="input-group mb-2">
                        <input class="d-block" type="text" required name="username" id="username"
                            placeholder="Email ou Login" />
                    </div>
                    <div class="input-group mb-2">
                        <input class="d-block" type="password" required name="password" id="password"
                            placeholder="Senha" />
                    </div>
                    <div class="input-group mb-2">
                        <input style="width: 100%; background-color: #1D3557; border-radius: 15px;"
                            class="btn btn-success" type="submit" value="Login" />
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

templates/session/signup.html
{% extends 'generic_base.html' %}

{% block title %} Cadastro {% endblock %}

{% block content %}
<div class="container-fluid">
  <div class="row">
    <div class="col-6">

    </div>
    <div class="col-6">
      <form action="{% url 'signup:new' %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
          <div class="input-group mb-2">
            <label for="username">Example file input</label>
            <input type="text" name="username" id="username" placeholder="Digite um nome de usuário..." required />
          </div>

          <div class="input-group mb-2">
            <label for="password">Example file input</label>
            <input type="password" name="password" id="password" placeholder="Digite uma senha" required />
          </div>

          <div class="input-group mb-2">
            <label for="email">Example file input</label>
            <input type="email" name="email" id="email" placeholder="Qual seu email?" required />
          </div>

          <div class="input-group mb-2">
            <label for="first_name">Example file input</label>
            <input type="text" name="first_name" id="first_name" placeholder="Qual seu nome?" required />
          </div>

          <div class="input-group mb-2">
            <label for="last_name">Example file input</label>
            <input type="text" name="last_name" id="last_name" placeholder="Qual seu sobre nome?" required />
          </div>

          <div class="input-group mb-2">
            <label for="photo">Example file input</label>
            <input type="file" name="photo" class="form-control-file" id="photo" placeholder="Escolha uma imagem" required />
          </div>


          <input type="submit" class="btn btn-success" value="Cadastrar" />

        </div>
    </div>
    </form>
  </div>
</div>
</div>
{% endblock %}